{{- $serviceAccount := .Values.serviceAccount }}
{{- $serviceAccountEnabled := $serviceAccount.create | default false }}
{{- if and $serviceAccount $serviceAccountEnabled }}
{{- template "common.serviceaccount" (list . "application.serviceAccount") -}}
{{- end }}
{{- define "application.serviceAccount" -}}
{{- end -}}
