image:
  registry: ghcr.io/technicaldomain
  name: github-app-jwt2token-controller
  tag: 1.0.0
  pullSecretsEnabled: false

healthCheck:
  liveness:
    disabled: true
  readiness:
    disabled: true
  startup:
    disabled: true

serviceAccount:
  create: true
