image:
  registry: ghcr.io/kharkevich
  name: github-app-jwt2token-controller
  tag: 1.1.1
  pullSecretsEnabled: false

healthCheck:
  liveness:
    disabled: true
  readiness:
    disabled: true
  startup:
    disabled: true

serviceAccount:
  create: true
