name: release
on:
  workflow_run:
    workflows: ["validate"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Release Helm Charts
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: charts
          skip_existing: true
          mark_as_latest: false
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Push Charts to GHCR
        run: |
          if [ -d ".cr-release-packages" ]; then
            for pkg in .cr-release-packages/*; do
              if [ -z "${pkg:-}" ]; then
                break
              fi
              helm push "${pkg}" oci://ghcr.io/technicaldomain/helm
            done
          fi
